version: '3.9'

services:
  app:
    build: .
    container_name: fastapi_rag_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - qdrant
    volumes:
      - ./data:/app/data

  redis:
    image: redis:7.2-alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_vector
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  celery:
    build: .
    container_name: celery_worker
    command: celery -A core.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    volumes:
      - ./app:/app

volumes:
  qdrant_data:
